CLS
PRINT
PRINT "WELCOME TO SASTA KBC"
INPUT "ARE YOU READY IF YES THEN TYPE Y IF NO THEN N";NY$
PRINT
IF NY$="Y" THEN
  PRINT "LET'S START"
  PRINT
  ELSE
  PRINT "BYE" 
  END
END IF
INPUT "ENTER YOUR NAME : ";N$
PRINT
PRINT "Q.1  WHO  IS THE PRIME MINISTER OF INDIA"
INPUT "A. ARNAV NILABH    B. NARENDRA MODI     C. ADYA SINGH     D. XYZ";Q1$
PRINT

IF Q1$="B" THEN
PRINT "WAH 1 CRORE TAALIYA BAJTI RAHNI CHAHIYE"
PRINT  
ELSE
PRINT "SO SAD GADHE"
PRINT
END IF

PRINT "Q.2 WHO IS THE FATHER OF NATION"
INPUT "A. NARENDRA MODI    B. MAHATMA GANDHI    C. RAHUL GANDHI   D. TEJASVI YADAV";Q2$
PRINT
IF Q2$="B" THEN 
PRINT "BETE BETE MOJ KARDI WAH BETE WAH"
PRINT
ELSE 
PRINT "TUJH SE NA HO PAYGA"
PRINT
END IF

PRINT "WHO IS THE PRESIDENT OF INDIA"
INPUT "A. RAJENDRA PRASAD    B. DRAUPATI MURMU     C. VANKAYIA NAIDU    D. NAMAN";Q3$
PRINT
IF Q3$="B" THEN
PRINT "KITNA JEETO GE MAHAN MAJA HI MAJA"
PRINT
ELSE 
PRINT "PADHO GE LIKHO GE HOGE NAWAB, khelo ge kudo ge hoge kharab"
PRINT
END IF 


PRINT "WELL PLAYED ";N$


